Ensure RSpec.configure is defined on loading rspec/sidekiq/matchers:
Loading "rspec/core" defines "RSpec.configure" when running, for example,
"rake db:test:prepare". Without loading "rspec/core", you get the
error: "undefined method `configure' for RSpec:Module"